# Generated by Django 4.1.2 on 2022-12-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='descrition',
        ),
        migrations.AddField(
            model_name='thing',
            name='description',
            field=models.TextField(blank=True, max_length=120),
        ),
    ]
